# @package _group_

common:
  fp16: true
  log_format: json
  log_interval: 100
  tensorboard_logdir: tb
  # wandb_project: ls-data2vec-fbank
  user_dir: /home/chenxie95/github/fairseq/examples/data2vec

checkpoint:
  save_interval: 1
  save_interval_updates: 0
  keep_interval_updates: 100
  no_epoch_checkpoints: false
  save_dir: /home/chenxie95/github/fairseq/outputs/data2vec/ls960_base_fbank_v2

task:
  _name: fbank_pretraining
  data: /mnt/data/librispeech/data4fairseq
  config_yaml: config.yaml
  # max_sample_size: 320000
  # min_sample_size: 32000
  # normalize: true

dataset:
  num_workers: 1
  # max_tokens: 7800000
  max_tokens: 80000
  # max_tokens: 1800000
  skip_invalid_size_inputs_valid_test: true
  validate_interval: 5
  required_batch_size_multiple: 1
  disable_validation: true

distributed_training:
  distributed_world_size: 1
  ddp_backend: legacy_ddp

criterion:
  _name: model
  log_keys:
    - ema_decay
    - target_var
    - pred_var

optimization:
  max_update: 400000
  update_freq: [1]
  # update_freq: [16]
  # lr: [0.0005]
  lr: [0.00005]

optimizer:
  _name: adam
  adam_betas: (0.9,0.98)
  adam_eps: 1e-06
  weight_decay: 0.01

lr_scheduler:
  _name: tri_stage
  phase_ratio: [0.03,0.9,0.07]

model:
  _name: data2vec_fbank
  extractor_mode: layer_norm
  encoder_layerdrop: 0.05
  dropout_input: 0.0
  dropout_features: 0.0
  feature_grad_mult: 1.0
  encoder_embed_dim: 768

  # encoder_embed_dim: 512
  # encoder_layers: 16
  # encoder_ffn_embed_dim: 2048
  # encoder_attention_heads: 8

  mask_prob: 0.65
  mask_length: 10

  loss_beta: 0
  loss_scale: null

  instance_norm_target_layer: true
  average_top_k_layers: 8

  pos_conv_depth: 5
  conv_pos: 95

  ema_decay: 0.999
  ema_end_decay: 0.9999
  ema_anneal_end_step: 30000
  ema_transformer_only: true
  ema_layers_only: true

  require_same_masks: true
  mask_dropout: 0

hydra:
    run:
        dir: ${checkpoint.save_dir}
